[Path]

;на работе
;PathWorkAccessMDB = D:\My_Project\SCRP\Admin\Win32\Debug\RudaData\Access.mdb
;PathWorkDataMDB   = D:\My_Project\SCRP\Admin\Win32\Debug\RudaData\Data.mdb
;PathWorkServerMDB = D:\My_Project\SCRP\Admin\Win32\Debug\RudaData\Server.mdb
;PathWorkStationMDB= D:\My_Project\SCRP\Admin\Win32\Debug\RudaData\WorkStation.mdb

;дома
PathWorkAccessMDB = C:\!Sasha\My_Project\SCRP\Admin\Win32\Debug\RudaData\Access.mdb
PathWorkDataMDB   = C:\!Sasha\My_Project\SCRP\Admin\Win32\Debug\RudaData\Data.mdb
PathWorkServerMDB = C:\!Sasha\My_Project\SCRP\Admin\Win32\Debug\RudaData\Server.mdb
PathWorkStationMdb= C:\!Sasha\My_Project\SCRP\Admin\Win32\Debug\RudaData\WorkStation.mdb

[Settings]
PrinterName=
                   